// <auto-generated />
using System;
using Cooperativa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cooperativa.Infrastructure.Migrations
{
    [DbContext(typeof(CooperativaDbContext))]
    [Migration("20261004204549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cooperativa.Models.Alocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CooperadoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FuncaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("CooperadoId");

                    b.HasIndex("FuncaoId");

                    b.ToTable("Alocacoes");
                });

            modelBuilder.Entity("Cooperativa.Models.ApuracaoPontoMensal", b =>
                {
                    b.Property<Guid>("CooperadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cooperado_id");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("date")
                        .HasColumnName("mes_ano");

                    b.Property<decimal>("QtdHorasExtras")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("qtd_horas_extras");

                    b.Property<decimal>("QtdHorasNormais")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("qtd_horas_normais");

                    b.Property<decimal>("QtdHorasNoturnas")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("qtd_horas_noturnas");

                    b.HasKey("CooperadoId", "MesAno");

                    b.ToTable("ApuracaoPontoMensal", (string)null);
                });

            modelBuilder.Entity("Cooperativa.Models.ConfiguracaoHoraNoturna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fim");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<bool>("HoraReduzida")
                        .HasColumnType("boolean")
                        .HasColumnName("hora_reduzida");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracaoHoraNoturna", (string)null);
                });

            modelBuilder.Entity("Cooperativa.Models.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Contato1Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Contato1Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Contato2Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Contato2Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmpresaNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<decimal>("ValorContrato")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Cooperativa.Models.ContratoFuncaoAdicional", b =>
                {
                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Guid>("FuncaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcao_id");

                    b.Property<Guid>("AdicionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("adicional_id");

                    b.HasKey("ContratoId", "FuncaoId", "AdicionalId");

                    b.HasIndex("AdicionalId");

                    b.HasIndex("FuncaoId");

                    b.ToTable("ContratoFuncaoAdicional", (string)null);
                });

            modelBuilder.Entity("Cooperativa.Models.Cooperado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("CertificadoReservista")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ChavePix")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ContaCorrente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeclaraImpostoRenda")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Equipe")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Escolaridade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("FuncaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Naturalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NomeConjuge")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("NumeroDependentes")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroIdentidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroPis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OrgaoEmissorIdentidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RegimeCasamento")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("SecaoEleitoral")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TituloEleitor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ZonaEleitoral")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("ContratoId");

                    b.HasIndex("FuncaoId");

                    b.ToTable("Cooperados");
                });

            modelBuilder.Entity("Cooperativa.Models.DespesaFolha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<decimal?>("TetoRetencao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("teto_retencao");

                    b.Property<string>("TipoCalculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_calculo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("DespesaFolha", (string)null);
                });

            modelBuilder.Entity("Cooperativa.Models.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NACIONAL")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .IsUnique();

                    b.ToTable("feriado", (string)null);
                });

            modelBuilder.Entity("Cooperativa.Models.FolhaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Adicional")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CooperadoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Descontos")
                        .HasColumnType("numeric");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text");

                    b.Property<decimal>("Salario")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CooperadoId");

                    b.ToTable("FolhasPagamento");
                });

            modelBuilder.Entity("Cooperativa.Models.Funcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cbo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Funcoes");
                });

            modelBuilder.Entity("Cooperativa.Models.JornadaContratual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<int>("DiasSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dias_semana");

                    b.Property<Guid>("FuncaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcao_id");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fim");

                    b.Property<TimeSpan?>("HoraFimIntervalo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fim_intervalo");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<TimeSpan?>("HoraInicioIntervalo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio_intervalo");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("ContratoId", "FuncaoId");

                    b.ToTable("JornadaContratual", (string)null);
                });

            modelBuilder.Entity("Cooperativa.Models.RegistroPonto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CooperadoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Entrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FimIntervalo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FimIntervalo");

                    b.Property<DateTime?>("InicioIntervalo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("InicioIntervalo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Ocorrencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Ocorrencia");

                    b.Property<DateTime?>("Saida")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CooperadoId");

                    b.ToTable("RegistrosPonto");
                });

            modelBuilder.Entity("Cooperativa.Models.RegraHoraExtra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<decimal>("PercentualHeComum")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(50.00m)
                        .HasColumnName("percentual_he_comum");

                    b.Property<decimal>("PercentualHeDomingoFeriado")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(100.00m)
                        .HasColumnName("percentual_he_domingo_feriado");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("regra_hora_extra", (string)null);
                });

            modelBuilder.Entity("Cooperativa.Models.Remuneracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("DataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("DataInicio");

                    b.Property<Guid>("FuncaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoRemuneracao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("ContratoId", "FuncaoId")
                        .IsUnique();

                    b.ToTable("Remuneracoes");
                });

            modelBuilder.Entity("Cooperativa.Models.TipoAdicional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("TipoCalculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_calculo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("TipoAdicional", (string)null);
                });

            modelBuilder.Entity("Cooperativa.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Cargo");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Celular");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ContratoId");

                    b.Property<Guid?>("CooperadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("CooperadoId");

                    b.Property<DateTime?>("DataIngresso")
                        .HasColumnType("date")
                        .HasColumnName("DataIngresso");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Equipe")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Equipe");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Login");

                    b.Property<DateTime?>("MfaCodigoExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MfaCodigoExpiracao");

                    b.Property<string>("MfaCodigoTemp")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("MfaCodigoTemp");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Perfil");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Senha");

                    b.Property<DateTime?>("TokenRedefinicaoExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TokenRedefinicaoExpiracao");

                    b.Property<string>("TokenRedefinicaoSenha")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TokenRedefinicaoSenha");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UltimoAcesso");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("CooperadoId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("UsuariosSistema", (string)null);
                });

            modelBuilder.Entity("Cooperativa.Models.UsuarioSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CooperadoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataIngresso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipe")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("MfaCodigoExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MfaCodigoTemp")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenRedefinicaoExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenRedefinicaoSenha")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Cooperativa.Models.Alocacao", b =>
                {
                    b.HasOne("Cooperativa.Models.Contrato", "Contrato")
                        .WithMany("Alocacoes")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.Models.Cooperado", "Cooperado")
                        .WithMany()
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.Models.Funcao", "Funcao")
                        .WithMany("Alocacoes")
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Cooperado");

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("Cooperativa.Models.ApuracaoPontoMensal", b =>
                {
                    b.HasOne("Cooperativa.Models.Cooperado", "Cooperado")
                        .WithMany()
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cooperado");
                });

            modelBuilder.Entity("Cooperativa.Models.ContratoFuncaoAdicional", b =>
                {
                    b.HasOne("Cooperativa.Models.TipoAdicional", "Adicional")
                        .WithMany()
                        .HasForeignKey("AdicionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.Models.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adicional");

                    b.Navigation("Contrato");

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("Cooperativa.Models.Cooperado", b =>
                {
                    b.HasOne("Cooperativa.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cooperativa.Models.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contrato");

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("Cooperativa.Models.FolhaPagamento", b =>
                {
                    b.HasOne("Cooperativa.Models.Cooperado", "Cooperado")
                        .WithMany()
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cooperado");
                });

            modelBuilder.Entity("Cooperativa.Models.JornadaContratual", b =>
                {
                    b.HasOne("Cooperativa.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.Models.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("Cooperativa.Models.RegistroPonto", b =>
                {
                    b.HasOne("Cooperativa.Models.Cooperado", "Cooperado")
                        .WithMany("RegistrosPonto")
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cooperado");
                });

            modelBuilder.Entity("Cooperativa.Models.RegraHoraExtra", b =>
                {
                    b.HasOne("Cooperativa.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Cooperativa.Models.Remuneracao", b =>
                {
                    b.HasOne("Cooperativa.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooperativa.Models.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("Cooperativa.Models.Usuario", b =>
                {
                    b.HasOne("Cooperativa.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cooperativa.Models.Cooperado", "Cooperado")
                        .WithMany()
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contrato");

                    b.Navigation("Cooperado");
                });

            modelBuilder.Entity("Cooperativa.Models.Contrato", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("Cooperativa.Models.Cooperado", b =>
                {
                    b.Navigation("RegistrosPonto");
                });

            modelBuilder.Entity("Cooperativa.Models.Funcao", b =>
                {
                    b.Navigation("Alocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
